#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-release}"
CONFIG_FILE="${VOICE_AI_DEPLOYMENT_CONFIG:-/etc/voice-ai-observability/deployment.env}"
RUNTIME_DIR=/etc/voice-ai-observability

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "Missing runtime deployment configuration: $CONFIG_FILE" >&2
  exit 1
fi

# This file is generated by infra/aws/deploy.sh from CloudFormation outputs. It
# contains resource identifiers, not application credentials.
# shellcheck disable=SC1090
source "$CONFIG_FILE"

required=(
  AWS_REGION AWS_ACCOUNT_ID APPLICATION_SECRET_ARN DATABASE_SECRET_ARN DATABASE_HOST
  DATABASE_PORT RUNTIME_IMAGE_PARAMETER INGESTION_QUEUE_URL ANALYSIS_QUEUE_URL LOG_GROUP_NAME
)
for name in "${required[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    echo "Missing deployment value: $name" >&2
    exit 1
  fi
done

install -d -m 700 "$RUNTIME_DIR"
umask 077

APP_JSON="$(aws secretsmanager get-secret-value \
  --region "$AWS_REGION" \
  --secret-id "$APPLICATION_SECRET_ARN" \
  --query SecretString \
  --output text)"
DB_JSON="$(aws secretsmanager get-secret-value \
  --region "$AWS_REGION" \
  --secret-id "$DATABASE_SECRET_ARN" \
  --query SecretString \
  --output text)"
IMAGE="$(aws ssm get-parameter \
  --region "$AWS_REGION" \
  --name "$RUNTIME_IMAGE_PARAMETER" \
  --query Parameter.Value \
  --output text)"

if [[ -z "$IMAGE" || "$IMAGE" == unconfigured ]]; then
  echo 'No immutable runtime image has been published.' >&2
  exit 1
fi

DB_USER="$(jq -r '.username' <<<"$DB_JSON")"
DB_PASSWORD="$(jq -r '.password' <<<"$DB_JSON")"
DATABASE_URL="$(python3 - "$DB_USER" "$DB_PASSWORD" "$DATABASE_HOST" "$DATABASE_PORT" <<'PY'
import sys
from urllib.parse import quote

user, password, host, port = sys.argv[1:]
print(f"postgresql://{quote(user, safe='')}:{quote(password, safe='')}@{host}:{port}/copilot?sslmode=verify-full")
PY
)"

write_secret() {
  local file="$1"
  local key="$2"
  local value
  value="$(jq -r --arg key "$key" '.[$key] // empty' <<<"$APP_JSON")"
  if [[ -n "$value" ]]; then printf '%s=%s\n' "$key" "$value" >>"$file"; fi
}

API_ENV="$RUNTIME_DIR/api.env"
INGESTION_ENV="$RUNTIME_DIR/ingestion-worker.env"
ANALYSIS_ENV="$RUNTIME_DIR/analysis-worker.env"

printf 'NODE_ENV=production\nPORT=3000\nAWS_REGION=%s\nDATABASE_URL=%s\nSQS_INGESTION_QUEUE_URL=%s\nSQS_ANALYSIS_QUEUE_URL=%s\nOUTBOX_PUBLISHER_ENABLED=true\n' \
  "$AWS_REGION" "$DATABASE_URL" "$INGESTION_QUEUE_URL" "$ANALYSIS_QUEUE_URL" >"$API_ENV"
for key in WEB_ORIGIN HIGHLEVEL_CLIENT_ID HIGHLEVEL_CLIENT_SECRET HIGHLEVEL_APP_ID HIGHLEVEL_REDIRECT_URI HIGHLEVEL_POST_INSTALL_REDIRECT_URI HIGHLEVEL_TOKEN_ENCRYPTION_KEY HIGHLEVEL_APP_SHARED_SECRET; do
  write_secret "$API_ENV" "$key"
done

printf 'NODE_ENV=production\nAWS_REGION=%s\nDATABASE_URL=%s\nSQS_INGESTION_QUEUE_URL=%s\n' \
  "$AWS_REGION" "$DATABASE_URL" "$INGESTION_QUEUE_URL" >"$INGESTION_ENV"

printf 'NODE_ENV=production\nAWS_REGION=%s\nDATABASE_URL=%s\nSQS_ANALYSIS_QUEUE_URL=%s\n' \
  "$AWS_REGION" "$DATABASE_URL" "$ANALYSIS_QUEUE_URL" >"$ANALYSIS_ENV"
for key in LLM_PROVIDER LLM_PROVIDER_ID LLM_BASE_URL LLM_MODEL LLM_API_KEY LLM_STRUCTURED_OUTPUT_MODE LLM_MAX_OUTPUT_TOKENS LLM_REQUEST_TIMEOUT_MS LLM_EXTRA_BODY_JSON ANALYSIS_CONCURRENCY; do
  write_secret "$ANALYSIS_ENV" "$key"
done
chmod 600 "$API_ENV" "$INGESTION_ENV" "$ANALYSIS_ENV"

aws ecr get-login-password --region "$AWS_REGION" |
  docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
docker pull "$IMAGE"

container_name() {
  case "$1" in
    api) printf 'voice-ai-api' ;;
    ingestion) printf 'voice-ai-ingestion-worker' ;;
    analysis) printf 'voice-ai-analysis-worker' ;;
    *) echo "Unknown runtime process: $1" >&2; return 1 ;;
  esac
}

stop_process() {
  local name
  name="$(container_name "$1")"
  if docker container inspect "$name" >/dev/null 2>&1; then
    docker stop --time 60 "$name" >/dev/null
    docker rm "$name" >/dev/null
  fi
}

start_process() {
  local process="$1"
  local image="$2"
  local name
  name="$(container_name "$process")"

  local common=(
    --detach
    --name "$name"
    --restart unless-stopped
    --stop-timeout 60
    --read-only
    --tmpfs /tmp:rw,noexec,nosuid,size=64m
    --cap-drop ALL
    --security-opt no-new-privileges
    --log-driver awslogs
    --log-opt "awslogs-region=$AWS_REGION"
    --log-opt "awslogs-group=$LOG_GROUP_NAME"
    --log-opt "awslogs-stream=$process"
  )

  case "$process" in
    api)
      docker run "${common[@]}" --memory 512m --env-file "$API_ENV" -p 3000:3000 \
        "$image" node apps/api/dist/main.js >/dev/null
      ;;
    ingestion)
      docker run "${common[@]}" --memory 384m --env-file "$INGESTION_ENV" \
        "$image" node apps/ingestion-worker/dist/main.js >/dev/null
      ;;
    analysis)
      docker run "${common[@]}" --memory 768m --env-file "$ANALYSIS_ENV" \
        "$image" node apps/analysis-worker/dist/main.js >/dev/null
      ;;
  esac
}

verify_process() {
  local process="$1"
  local name
  name="$(container_name "$process")"
  if [[ "$process" == api ]]; then
    for _ in {1..30}; do
      if curl --fail --silent http://127.0.0.1:3000/api/health/ready >/dev/null; then return 0; fi
      sleep 2
    done
    return 1
  fi

  sleep 3
  [[ "$(docker inspect --format '{{.State.Running}}' "$name" 2>/dev/null)" == true ]]
}

replace_process() {
  local process="$1"
  local name old_image desired_image
  name="$(container_name "$process")"
  old_image="$(docker inspect --format '{{.Config.Image}}' "$name" 2>/dev/null || true)"
  desired_image="$IMAGE"
  if [[ "$MODE" == restart-* && -n "$old_image" ]]; then desired_image="$old_image"; fi
  stop_process "$process"

  if start_process "$process" "$desired_image" && verify_process "$process"; then return 0; fi

  echo "The new $process process failed its readiness check." >&2
  stop_process "$process"
  if [[ -n "$old_image" && "$MODE" != release-migrate ]]; then
    echo "Rolling $process back to $old_image." >&2
    start_process "$process" "$old_image"
    verify_process "$process"
  fi
  return 1
}

restore_process() {
  local process="$1"
  local image="$2"
  stop_process "$process"
  if [[ -z "$image" ]]; then return 0; fi
  start_process "$process" "$image"
  verify_process "$process"
}

release_all() {
  local old_analysis old_ingestion
  old_analysis="$(docker inspect --format '{{.Config.Image}}' "$(container_name analysis)" 2>/dev/null || true)"
  old_ingestion="$(docker inspect --format '{{.Config.Image}}' "$(container_name ingestion)" 2>/dev/null || true)"

  if ! replace_process analysis; then return 1; fi
  if ! replace_process ingestion; then
    echo 'Restoring the previous analysis-worker release.' >&2
    restore_process analysis "$old_analysis" || echo 'Analysis-worker rollback failed.' >&2
    return 1
  fi
  if ! replace_process api; then
    echo 'Restoring the previous worker release.' >&2
    restore_process ingestion "$old_ingestion" || echo 'Ingestion-worker rollback failed.' >&2
    restore_process analysis "$old_analysis" || echo 'Analysis-worker rollback failed.' >&2
    return 1
  fi

}

run_migrations() {
  docker run --rm --env-file "$API_ENV" "$IMAGE" node apps/api/dist/database/migrate.js
}

case "$MODE" in
  release) release_all ;;
  release-migrate)
    stop_process analysis
    stop_process ingestion
    stop_process api
    run_migrations
    start_process api "$IMAGE"
    verify_process api
    start_process ingestion "$IMAGE"
    verify_process ingestion
    start_process analysis "$IMAGE"
    verify_process analysis
    ;;
  restart-api) replace_process api ;;
  restart-ingestion) replace_process ingestion ;;
  restart-analysis) replace_process analysis ;;
  restart-all)
    replace_process analysis
    replace_process ingestion
    replace_process api
    ;;
  *)
    echo "Usage: $0 {release|release-migrate|restart-api|restart-ingestion|restart-analysis|restart-all}" >&2
    exit 2
    ;;
esac

docker image prune --all --force --filter until=168h >/dev/null
printf 'Runtime deployment completed with image %s using mode %s.\n' "$IMAGE" "$MODE"
